version: '3.7'
x-environment:
  &database_credentials
  POSTGRES_USER: ${DB_USER:-rest-api}
  POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
  POSTGRES_DB: ${DB_NAME:-api-db}

services:
  spring-boot-rest-api-starter-db:
    image:  postgres:11-alpine
    environment:
      *database_credentials
    ports:
      - 5432:5432
    networks:
      - spring-boot-rest-api-starter-network
  spring-boot-rest-api-starter:
    build: .
    image: spring-boot-rest-api-starter:latest
    environment:
      << : *database_credentials
      ACTIVE_PROFILE: ${PROFILE:-dev}
      JVM_OPTS:
    ports:
      - 8080:8080
    depends_on:
      - spring-boot-rest-api-starter-db
    networks:
      - spring-boot-rest-api-starter-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - spring-boot-rest-api-starter-network
    restart: unless-stopped
networks:
  spring-boot-rest-api-starter-network: